//! CRIT-03's last item: MANUAL.md's description of the MCP surface is
//! GENERATED from the server's own declared schemas, in a test, so it
//! cannot drift.
//!
//! The finding was that "the documented JSON record schema does not match
//! what is emitted": the manual described a record with fields the server
//! never sent and omitted `delay_slot`, which it always could have. A
//! hand-written table cannot stay true across a release; one rendered from
//! `tools/list` and from the declared `outputSchema` can only be wrong if
//! the server is.
//!
//! `UPDATE_MANUAL=1 cargo test -p rf-mcp --test manual_schema` rewrites the
//! block between the two markers. Nothing outside them is touched.

mod support;

use serde_json::{json, Value};

use support::McpChild;

const MANUAL: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/../../MANUAL.md");
const BEGIN: &str = "<!-- BEGIN GENERATED: mcp-surface -->";
const END: &str = "<!-- END GENERATED: mcp-surface -->";

/// Collapse a schema description to one line for a table cell: the first
/// sentence, hard-cut at 150 characters with an ellipsis only when that
/// sentence is itself longer than a table cell should be.
fn one_line(s: &str) -> String {
    let flat = s.split_whitespace().collect::<Vec<_>>().join(" ");
    let flat = flat.replace('|', "\\|");
    let sentence = match flat.find(". ") {
        Some(i) => flat.get(..=i).unwrap_or(&flat).to_string(),
        None => flat,
    };
    match sentence.char_indices().find(|(i, _)| *i >= 150) {
        Some((i, _)) => format!("{}…", sentence.get(..i).unwrap_or(&sentence).trim_end()),
        None => sentence,
    }
}

/// Render a property's type the way a reader needs it, not the way JSON
/// Schema spells it.
fn type_of(schema: &Value, defs: &Value) -> String {
    if let Some(r) = schema.get("$ref").and_then(Value::as_str) {
        let name = r.rsplit('/').next().unwrap_or(r);
        if let Some(target) = defs.get(name) {
            if let Some(Value::Array(vals)) = target.get("enum") {
                let names: Vec<String> = vals
                    .iter()
                    .map(|v| format!("`{}`", v.as_str().unwrap_or_default()))
                    .collect();
                return names.join(" \\| ");
            }
        }
        return format!("`{name}`");
    }
    if let Some(Value::Array(branches)) = schema.get("anyOf") {
        let parts: Vec<String> = branches.iter().map(|b| type_of(b, defs)).collect();
        return parts.join(" \\| ");
    }
    match schema.get("type") {
        Some(Value::String(t)) if t == "array" => {
            let item = schema
                .get("items")
                .map(|i| type_of(i, defs))
                .unwrap_or_else(|| "any".to_string());
            format!("array of {item}")
        }
        Some(Value::String(t)) => t.clone(),
        Some(Value::Array(ts)) => ts
            .iter()
            .filter_map(Value::as_str)
            .collect::<Vec<_>>()
            .join(" \\| "),
        _ => "any".to_string(),
    }
}

fn render(tools: &[Value], record: &Value, defs: &Value) -> String {
    let mut out = String::new();
    out.push_str(BEGIN);
    out.push_str(
        "\n<!-- Generated by `cargo test -p rf-mcp --test manual_schema`. \
         Do not edit by hand: the test regenerates it from the server's own \
         tools/list and outputSchema and fails if this block has drifted. -->\n\n",
    );
    out.push_str(&format!("**The {} tools:**\n\n", tools.len()));
    out.push_str("| Tool | Required parameters | What it does |\n|---|---|---|\n");
    for t in tools {
        let name = t["name"].as_str().unwrap_or_default();
        let req: Vec<String> = t["inputSchema"]["required"]
            .as_array()
            .map(|a| {
                a.iter()
                    .filter_map(Value::as_str)
                    .map(|s| format!("`{s}`"))
                    .collect()
            })
            .unwrap_or_default();
        let req = if req.is_empty() {
            "(none)".to_string()
        } else {
            req.join(", ")
        };
        let desc = one_line(t["description"].as_str().unwrap_or_default());
        out.push_str(&format!("| `{name}` | {req} | {desc} |\n"));
    }

    out.push_str(
        "\n**The gadget record.** Every gadget-returning tool emits this shape, and \
         emits it *invariantly*: a field whose value is unknown is `null`, never \
         absent, so a parser written against one response works on every other.\n\n",
    );
    out.push_str("| Field | Type | Meaning |\n|---|---|---|\n");
    let props = record["properties"].as_object().expect("record properties");
    // `required` preserves the struct's declaration order and covers every
    // non-nullable field; the nullable ones (which schemars leaves out of
    // `required`) follow, sorted, so the table is COMPLETE. A table that
    // silently omitted `section` or `arch` would repeat the finding.
    let mut order: Vec<String> = record["required"]
        .as_array()
        .map(|a| {
            a.iter()
                .filter_map(Value::as_str)
                .map(str::to_string)
                .collect()
        })
        .unwrap_or_default();
    let mut nullable: Vec<String> = props
        .keys()
        .filter(|k| !order.contains(k))
        .cloned()
        .collect();
    nullable.sort();
    order.extend(nullable);
    assert_eq!(
        order.len(),
        props.len(),
        "the generated table would omit a field"
    );
    for name in order {
        let Some(p) = props.get(&name) else { continue };
        let desc = one_line(p.get("description").and_then(Value::as_str).unwrap_or(""));
        out.push_str(&format!("| `{name}` | {} | {desc} |\n", type_of(p, defs)));
    }
    out.push('\n');
    out.push_str(END);
    out
}

/// The manual's MCP-surface block is exactly what the server declares.
#[tokio::test]
async fn manual_mcp_section_is_generated_from_the_schema() {
    let mut mcp = McpChild::spawn().await;
    let list = mcp.rpc(1, "tools/list", json!({})).await;
    let mut tools: Vec<Value> = list["result"]["tools"].as_array().expect("tools").clone();
    tools.sort_by(|a, b| a["name"].as_str().cmp(&b["name"].as_str()));

    let scan_schema = tools
        .iter()
        .find(|t| t["name"] == "find_gadgets")
        .expect("find_gadgets")["outputSchema"]
        .clone();
    let defs = scan_schema["$defs"].clone();
    let record = defs["GadgetRecord"].clone();
    assert!(
        record["properties"].is_object(),
        "the gadget record is not a $def any more: {scan_schema}"
    );

    let block = render(&tools, &record, &defs);
    let manual = std::fs::read_to_string(MANUAL).expect(MANUAL);
    let start = manual
        .find(BEGIN)
        .unwrap_or_else(|| panic!("{MANUAL} has no {BEGIN} marker"));
    let end = manual
        .find(END)
        .unwrap_or_else(|| panic!("{MANUAL} has no {END} marker"))
        + END.len();
    let current = manual.get(start..end).expect("marker range");

    if std::env::var("UPDATE_MANUAL").is_ok() {
        let head = manual.get(..start).unwrap_or_default();
        let tail = manual.get(end..).unwrap_or_default();
        std::fs::write(MANUAL, format!("{head}{block}{tail}")).expect("rewrite MANUAL.md");
        return;
    }
    assert_eq!(
        current, block,
        "MANUAL.md's MCP-surface block has drifted from the server's declared schema; \
         regenerate with UPDATE_MANUAL=1 cargo test -p rf-mcp --test manual_schema"
    );

    // The specific claims CRIT-03 says the manual got wrong.
    for field in [
        "id",
        "vaddr",
        "vaddr_u64",
        "delay_slot",
        "section",
        "arch",
        "class",
        "stack_delta",
        "regs_from_stack",
        "terminator",
    ] {
        assert!(
            current.contains(&format!("| `{field}` |")),
            "the generated record table does not document {field}"
        );
    }
}
