//! rf-chain — ROP chain builders (Phase 4a, PLAN.md §6.2).
//!
//! **Chain IR first** (the review-driven design): builders produce a
//! structured [`RopChain`] — a `Vec<ChainWord>` where every word knows its
//! kind, its comment, and which gadget it came from — and renderers turn
//! the IR into ROPgadget-compatible Python exploit text, JSON, or raw
//! little-endian bytes. ROPgadget's stdout-text design is why nothing can
//! consume its chains programmatically; the IR is the fix.
//!
//! Invariants are checked at build/validation time and reported as
//! structured [`ChainError`]s, never panics:
//!   * every `GadgetAddr` word's value is the vaddr of an actually-reported
//!     gadget (checked against the scan's vaddr universe);
//!   * every non-gadget word (`Immediate` / `DataAddr` / `Padding`) must be
//!     badbyte-free when bad bytes are configured — bad bytes are a
//!     property of the final packed word (PLAN.md §6.4);
//!   * per-target invariant hooks ([`ChainInvariant`]) are the Phase 4b
//!     extension point — the Win64 16-byte stack-alignment invariant lands
//!     there; Linux execve needs no extra invariants.

use rf_core::Arch;
use serde::Serialize;
use std::collections::HashSet;

pub mod linux;
pub mod windows;

pub use linux::{build_linux_execve, DataSection};
pub use windows::{build_windows_virtualprotect, WinChainOpts};

/// What a chain word is for.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum WordKind {
    /// Address of a gadget in the scanned binary.
    GadgetAddr,
    /// Immediate constant rendered as a Python bytes literal (e.g. the
    /// packed "/bin//sh" string).
    Immediate,
    /// Address-like constant rendered as a `pack()` word: data-section
    /// locations (`@ .data`), and on Windows also numeric stack arguments.
    DataAddr,
    /// Control-flow target that is not a gadget from this binary: an API
    /// entry address (`--api-addr`), a shellcode/return address. Rendered
    /// as a `pack()` word; badbyte-checked like DataAddr.
    CodeAddr,
    /// Filler consumed by a `pop` in a gadget's tail, shadow space, or a
    /// stack-alignment word.
    Padding,
}

fn hex_u64<S: serde::Serializer>(v: &u64, s: S) -> Result<S::Ok, S::Error> {
    s.serialize_str(&format!("0x{v:x}"))
}

/// One machine word of the chain (8 bytes on x64, 4 on x86).
#[derive(Debug, Clone, Serialize)]
pub struct ChainWord {
    #[serde(serialize_with = "hex_u64")]
    pub value: u64,
    pub kind: WordKind,
    pub comment: String,
    /// Index into [`RopChain::gadgets`] for `GadgetAddr` words.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub source_gadget: Option<usize>,
}

/// A gadget referenced by the chain.
#[derive(Debug, Clone, Serialize)]
pub struct GadgetRef {
    #[serde(serialize_with = "hex_u64")]
    pub vaddr: u64,
    pub text: String,
}

/// A generated ROP chain in target-independent form.
#[derive(Debug, Clone, Serialize)]
pub struct RopChain {
    /// e.g. "x86" / "x64".
    pub arch: String,
    /// Human-readable summary of what the chain does.
    pub description: String,
    /// Second line of the python script header. Linux builders keep
    /// "# execve generated by ROPgadget" verbatim for byte parity; Windows
    /// builders use their own comment.
    pub script_comment: String,
    /// Bytes per word (4 or 8).
    pub word_size: usize,
    pub words: Vec<ChainWord>,
    /// Distinct gadgets referenced by `GadgetAddr` words, in order of
    /// first reference; `ChainWord::source_gadget` indexes this list.
    pub gadgets: Vec<GadgetRef>,
}

/// Structured chain-building failure. Builders never panic and never emit
/// partial garbage: any missing gadget or violated invariant is an `Err`.
#[derive(Debug, thiserror::Error)]
pub enum ChainError {
    /// Mirrors ropmaker.py:23-40 dispatch: only ELF x86/x64 are supported.
    #[error("arch {arch} / format {format} not supported yet for the rop chain generation")]
    Unsupported { arch: String, format: String },
    /// A required gadget is absent from the scan output.
    #[error("can't find a suitable gadget: {0}")]
    MissingGadget(String),
    /// No `.data` (and no fallback writable section) for the string write.
    #[error("can't find a writable section")]
    NoWritableSection,
    /// An IR invariant was violated (see [`RopChain::validate`]).
    #[error("chain word {index} (0x{value:016x}, {kind:?}): {reason}")]
    InvalidWord {
        index: usize,
        value: u64,
        kind: WordKind,
        reason: String,
    },
}

/// Per-target invariant hook (Phase 4b extension point). Receives the full
/// chain; returns `Err` to reject it. Example for Phase 4b (Win64):
/// "rsp must be 16-byte aligned at the VirtualProtect call site".
pub type ChainInvariant<'a> = &'a dyn Fn(&RopChain) -> Result<(), ChainError>;

impl RopChain {
    /// Check the build-time invariants:
    ///   * every `GadgetAddr` word points at a real reported gadget
    ///     (`universe` = the scan's vaddr set) and its `source_gadget`
    ///     index agrees;
    ///   * every non-gadget word is badbyte-free (packed at `word_size`).
    pub fn validate(&self, universe: &HashSet<u64>, badbytes: &[u8]) -> Result<(), ChainError> {
        self.validate_with(universe, badbytes, &[])
    }

    /// [`validate`](Self::validate) plus per-target invariant hooks.
    pub fn validate_with(
        &self,
        universe: &HashSet<u64>,
        badbytes: &[u8],
        hooks: &[ChainInvariant],
    ) -> Result<(), ChainError> {
        for (i, w) in self.words.iter().enumerate() {
            let invalid = |reason: String| ChainError::InvalidWord {
                index: i,
                value: w.value,
                kind: w.kind,
                reason,
            };
            match w.kind {
                WordKind::GadgetAddr => {
                    let idx = w
                        .source_gadget
                        .ok_or_else(|| invalid("gadget word without source_gadget".to_string()))?;
                    let g = self
                        .gadgets
                        .get(idx)
                        .ok_or_else(|| invalid(format!("source_gadget {idx} out of range")))?;
                    if g.vaddr != w.value {
                        return Err(invalid(format!(
                            "value {:#x} != gadgets[{idx}].vaddr {:#x}",
                            w.value, g.vaddr
                        )));
                    }
                    if !universe.contains(&w.value) {
                        return Err(invalid(format!(
                            "vaddr {:#x} is not in the scan output",
                            w.value
                        )));
                    }
                }
                WordKind::Immediate
                | WordKind::DataAddr
                | WordKind::CodeAddr
                | WordKind::Padding => {
                    if !badbytes.is_empty() {
                        let packed = &w.value.to_le_bytes()[..self.word_size];
                        if let Some(b) = packed.iter().find(|b| badbytes.contains(b)) {
                            return Err(invalid(format!(
                                "packed word contains bad byte 0x{b:02x}"
                            )));
                        }
                    }
                }
            }
        }
        for hook in hooks {
            hook(self)?;
        }
        Ok(())
    }

    /// The scan's vaddr universe, for [`validate`](Self::validate).
    pub fn universe_from(gadgets: &[rf_scan::Gadget]) -> HashSet<u64> {
        gadgets.iter().map(|g| g.vaddr).collect()
    }

    fn pack_char(&self) -> (char, usize) {
        match self.word_size {
            4 => ('I', 8),
            _ => ('Q', 16),
        }
    }

    /// ROPgadget-compatible Python exploit script (ropmakerx64.py output
    /// structure: the `from struct import pack` header, `p = b''`, and
    /// `p += pack('<Q', 0x...) # ...` lines; string immediates render as
    /// `p += b'...'`). The header comment line comes from
    /// [`RopChain::script_comment`].
    ///
    /// Every line is emitted at column 0 (ROB-05: ropmaker indents padding
    /// lines with a literal tab, which makes the script an
    /// `IndentationError` at module level — we deliberately diverge), and
    /// every comment goes through [`py_comment`] first (ROB-01: comment
    /// text is derived from the analysed binary, so a newline in it would
    /// otherwise close the comment and inject top-level Python).
    pub fn to_python(&self) -> String {
        let (c, w) = self.pack_char();
        let mask = if self.word_size >= 8 {
            u64::MAX
        } else {
            (1u64 << (self.word_size * 8)) - 1
        };
        let mut header = py_comment(&self.script_comment);
        if !header.starts_with('#') {
            header.insert_str(0, "# ");
        }
        let mut out = format!(
            "#!/usr/bin/env python3\n{header}\n\nfrom struct import pack\n\n# Padding goes here\np = b''\n\n"
        );
        for word in &self.words {
            let value = word.value & mask;
            match word.kind {
                WordKind::Immediate => {
                    let bytes = &value.to_le_bytes()[..self.word_size];
                    out.push_str(&format!("p += b'{}'\n", py_bytes_escape(bytes)));
                }
                WordKind::GadgetAddr
                | WordKind::DataAddr
                | WordKind::CodeAddr
                | WordKind::Padding => {
                    out.push_str(&format!(
                        "p += pack('<{c}', 0x{:0w$x}) # {}\n",
                        value,
                        py_comment(&word.comment)
                    ));
                }
            }
        }
        out
    }

    /// JSON form of the IR.
    pub fn to_json(&self) -> serde_json::Value {
        serde_json::to_value(self).unwrap()
    }

    /// Raw little-endian bytes of the chain (what `p` contains at runtime).
    pub fn to_bytes(&self) -> Vec<u8> {
        let mut out = Vec::with_capacity(self.words.len() * self.word_size);
        for w in &self.words {
            out.extend_from_slice(&w.value.to_le_bytes()[..self.word_size]);
        }
        out
    }
}

/// Maximum length of a comment rendered into the generated Python script.
pub const PY_COMMENT_MAX: usize = 64;

/// Sanitise a string for use inside a `#` comment of the generated Python
/// script (ROB-01).
///
/// Comment text is derived from the analysed binary — the PE import DLL
/// name ([`rf_core::PeImport::dll`], copied verbatim out of the import
/// descriptor) and the disassembled gadget text both end up here. A
/// newline in such a string terminates the `#` comment and turns whatever
/// follows into top-level Python that the user then executes, so every
/// character outside printable ASCII (`0x20..=0x7e`) — newlines and
/// carriage returns included — is dropped rather than escaped, and the
/// result is truncated to [`PY_COMMENT_MAX`] characters.
pub fn py_comment(s: &str) -> String {
    s.chars()
        .filter(|c| (' '..='~').contains(c))
        .take(PY_COMMENT_MAX)
        .collect()
}

/// Render bytes as a Python `b'...'` literal body (ROPgadget only ever
/// emits printable ASCII here, but escape defensively).
fn py_bytes_escape(bytes: &[u8]) -> String {
    let mut out = String::new();
    for &b in bytes {
        match b {
            b'\'' => out.push_str("\\'"),
            b'\\' => out.push_str("\\\\"),
            0x20..=0x7e => out.push(b as char),
            _ => out.push_str(&format!("\\x{b:02x}")),
        }
    }
    out
}

/// Arch display name used in the IR (`"x86"` / `"x64"` / ...).
pub fn arch_name(arch: Arch) -> String {
    match arch {
        Arch::X86 => "x86",
        Arch::X64 => "x64",
        Arch::Arm => "arm",
        Arch::ArmThumb => "arm-thumb",
        Arch::Arm64 => "arm64",
        Arch::Mips32 => "mips32",
        Arch::Mips64 => "mips64",
        Arch::Ppc32 => "ppc32",
        Arch::Ppc64 => "ppc64",
        Arch::Sparc => "sparc",
        Arch::Sparc64 => "sparc64",
        Arch::SparcV9 => "sparcv9",
        Arch::RiscV32 => "riscv32",
        Arch::RiscV64 => "riscv64",
    }
    .to_string()
}

#[cfg(test)]
pub(crate) mod tests {
    use super::*;

    /// Pure-Rust "is this a flat, un-injected script?" check, shared with
    /// the windows builder tests. Every generated script is a flat
    /// sequence of top-level statements, so every line must be blank, a
    /// comment, one of the two fixed header statements, or a `p += …`
    /// append — and no line may be indented (ROB-05) or introduce a
    /// statement of its own (ROB-01). A script that passes this also
    /// parses as Python.
    pub(crate) fn assert_flat_python_script(py: &str) {
        let mut lines = py.lines();
        assert_eq!(lines.next(), Some("#!/usr/bin/env python3"));
        let header = lines.next().unwrap_or("");
        assert!(
            header.starts_with('#'),
            "header is not a comment: {header:?}"
        );
        for (i, line) in py.lines().enumerate() {
            assert!(
                !(line.starts_with(' ') || line.starts_with('\t')),
                "line {i} is indented at module level: {line:?}"
            );
            let ok = line.is_empty()
                || line.starts_with('#')
                || line == "from struct import pack"
                || line == "p = b''"
                || line.starts_with("p += ");
            assert!(ok, "line {i} is not a header or append statement: {line:?}");
        }
    }

    /// Assert `needle` never occurs in statement position: on every line
    /// that contains it, the line's first `#` comes first.
    pub(crate) fn assert_only_in_comment(py: &str, needle: &str) {
        for line in py.lines() {
            let Some(at) = line.find(needle) else {
                continue;
            };
            let hash = line
                .find('#')
                .unwrap_or_else(|| panic!("{needle:?} outside any comment: {line:?}"));
            assert!(hash < at, "{needle:?} in statement position: {line:?}");
        }
    }

    /// The interpreter to cross-check generated scripts with:
    /// `$RF_CHAIN_PYTHON` when set, else `python`, else `python3`.
    /// Candidates are probed with `-c "import ast"` so a non-working stub
    /// (the Windows Store alias) counts as absent.
    fn python_interpreter() -> Option<String> {
        let candidates = match std::env::var("RF_CHAIN_PYTHON") {
            Ok(p) => vec![p],
            Err(_) => vec!["python".to_string(), "python3".to_string()],
        };
        candidates.into_iter().find(|exe| {
            std::process::Command::new(exe)
                .args(["-c", "import ast"])
                .output()
                .map(|o| o.status.success())
                .unwrap_or(false)
        })
    }

    /// Optional cross-check: `ast.parse` the generated script with a real
    /// interpreter. A no-op when no interpreter can be spawned, so the
    /// suite never depends on a Python installation — the pure-Rust
    /// [`assert_flat_python_script`] is the load-bearing assertion.
    pub(crate) fn assert_python_parses(py: &str) {
        let Some(exe) = python_interpreter() else {
            return;
        };
        // pid + a per-process counter: tests run in parallel threads.
        static SEQ: std::sync::atomic::AtomicUsize = std::sync::atomic::AtomicUsize::new(0);
        let n = SEQ.fetch_add(1, std::sync::atomic::Ordering::Relaxed);
        let mut path = std::env::temp_dir();
        path.push(format!("rf-chain-script-{}-{n}.py", std::process::id()));
        std::fs::write(&path, py).unwrap();
        let out = std::process::Command::new(&exe)
            .args(["-c", "import ast,sys;ast.parse(open(sys.argv[1]).read())"])
            .arg(&path)
            .output()
            .unwrap();
        let _ = std::fs::remove_file(&path);
        assert!(
            out.status.success(),
            "{exe} rejected the generated script: {}\n--- script ---\n{py}",
            String::from_utf8_lossy(&out.stderr)
        );
    }

    fn chain_fixture() -> RopChain {
        RopChain {
            arch: "x64".to_string(),
            description: "test".to_string(),
            script_comment: "# execve generated by ROPgadget".to_string(),
            word_size: 8,
            gadgets: vec![GadgetRef {
                vaddr: 0x401000,
                text: "pop rdi ; ret".to_string(),
            }],
            words: vec![
                ChainWord {
                    value: 0x401000,
                    kind: WordKind::GadgetAddr,
                    comment: "pop rdi ; ret".to_string(),
                    source_gadget: Some(0),
                },
                ChainWord {
                    value: 0x6bc080,
                    kind: WordKind::DataAddr,
                    comment: "@ .data".to_string(),
                    source_gadget: None,
                },
                ChainWord {
                    value: 0x4141414141414141,
                    kind: WordKind::Padding,
                    comment: "padding".to_string(),
                    source_gadget: None,
                },
            ],
        }
    }

    #[test]
    fn validate_accepts_wellformed() {
        let c = chain_fixture();
        let universe: HashSet<u64> = [0x401000].into_iter().collect();
        c.validate(&universe, &[]).unwrap();
    }

    #[test]
    fn validate_rejects_unknown_gadget_addr() {
        let mut c = chain_fixture();
        c.words[0].value = 0xdead0000;
        let universe: HashSet<u64> = [0x401000].into_iter().collect();
        let err = c.validate(&universe, &[]).unwrap_err();
        assert!(matches!(err, ChainError::InvalidWord { index: 0, .. }));
    }

    #[test]
    fn validate_rejects_source_mismatch_and_missing_index() {
        let universe: HashSet<u64> = [0x401000, 0x401002].into_iter().collect();
        let mut c = chain_fixture();
        c.words[0].value = 0x401002; // in universe but != gadgets[0].vaddr
        assert!(c.validate(&universe, &[]).is_err());
        let mut c = chain_fixture();
        c.words[0].source_gadget = None;
        assert!(c.validate(&universe, &[]).is_err());
        let mut c = chain_fixture();
        c.words[0].source_gadget = Some(7);
        assert!(c.validate(&universe, &[]).is_err());
    }

    #[test]
    fn validate_rejects_badbyte_immediates_and_data_addrs() {
        let c = chain_fixture();
        let universe: HashSet<u64> = [0x401000].into_iter().collect();
        // 0x6bc080 packs to 80 c0 6b 00 ... — byte 00 is bad
        let err = c.validate(&universe, &[0x00]).unwrap_err();
        assert!(matches!(err, ChainError::InvalidWord { index: 1, .. }));
        // 0x41 in the padding constant
        let err = c.validate(&universe, &[0x41]).unwrap_err();
        assert!(matches!(err, ChainError::InvalidWord { index: 2, .. }));
        // gadget words are not re-checked (they passed scan-time badbytes)
        c.validate(&universe, &[0x10]).unwrap();
    }

    #[test]
    fn invariant_hooks_run() {
        let c = chain_fixture();
        let universe: HashSet<u64> = [0x401000].into_iter().collect();
        let reject: ChainInvariant = &|_| {
            Err(ChainError::InvalidWord {
                index: 0,
                value: 0,
                kind: WordKind::GadgetAddr,
                reason: "hook says no".to_string(),
            })
        };
        let err = c.validate_with(&universe, &[], &[reject]).unwrap_err();
        assert!(err.to_string().contains("hook says no"));
    }

    #[test]
    fn python_renderer_matches_ropmaker_format() {
        let c = chain_fixture();
        let py = c.to_python();
        assert!(py.starts_with(
            "#!/usr/bin/env python3\n# execve generated by ROPgadget\n\nfrom struct import pack\n\n# Padding goes here\np = b''\n\n"
        ));
        assert!(py.contains("p += pack('<Q', 0x0000000000401000) # pop rdi ; ret\n"));
        assert!(py.contains("p += pack('<Q', 0x00000000006bc080) # @ .data\n"));
    }

    /// ROB-05: ropmaker indents padding lines with a literal tab, which
    /// makes every script with a padding word an `IndentationError`. We
    /// deliberately diverge — every line is at column 0.
    #[test]
    fn padding_lines_are_not_indented() {
        let c = chain_fixture();
        let py = c.to_python();
        assert!(py.contains("p += pack('<Q', 0x4141414141414141) # padding\n"));
        assert!(!py.contains('\t'), "{py}");
        assert_flat_python_script(&py);
        assert_python_parses(&py);
    }

    #[test]
    fn x86_pack_format() {
        let mut c = chain_fixture();
        c.word_size = 4;
        let py = c.to_python();
        assert!(py.contains("pack('<I', 0x00401000)"));
        assert!(py.contains("p += pack('<I', 0x41414141) # padding\n"));
        assert!(!py.contains('\t'), "{py}");
        // raw bytes are 4-byte LE words
        let raw = c.to_bytes();
        assert_eq!(raw.len(), 12);
        assert_eq!(&raw[0..4], &0x401000u32.to_le_bytes());
    }

    #[test]
    fn immediate_renders_as_python_bytes() {
        let mut c = chain_fixture();
        c.words.push(ChainWord {
            value: u64::from_le_bytes(*b"/bin//sh"),
            kind: WordKind::Immediate,
            comment: String::new(),
            source_gadget: None,
        });
        let py = c.to_python();
        assert!(py.contains("p += b'/bin//sh'\n"));
        let raw = c.to_bytes();
        assert_eq!(&raw[24..32], b"/bin//sh");
    }

    /// ROB-01: the sanitiser itself.
    #[test]
    fn py_comment_strips_control_chars_and_truncates() {
        assert_eq!(
            py_comment("@ IAT VirtualProtect (KERNEL32.dll)"),
            "@ IAT VirtualProtect (KERNEL32.dll)"
        );
        // newlines, carriage returns and tabs are removed, not escaped
        assert_eq!(
            py_comment("KERNEL32\nimport os\r\nx\t.dll"),
            "KERNEL32import osx.dll"
        );
        // everything else outside 0x20..=0x7e goes too (NUL, DEL, non-ASCII)
        assert_eq!(py_comment("a\u{0}b\u{7f}c\u{e9}d\u{1f600}"), "abcd");
        assert_eq!(py_comment(&"A".repeat(4096)).len(), PY_COMMENT_MAX);
    }

    /// ROB-01: a comment carried in the IR cannot break out of the `#`,
    /// whichever word kind or the script header carries it.
    #[test]
    fn tainted_comments_cannot_escape_the_python_comment() {
        let mut c = chain_fixture();
        c.script_comment = "# hdr\nimport os\nos.system('id')".to_string();
        c.words[0].comment = "pop rdi ; ret\nimport os\nos.system('id')".to_string();
        c.words[1].comment = "@ .data\nimport os\nos.system('id')".to_string();
        c.words[2].comment = "padding\nimport os\nos.system('id')".to_string();
        let py = c.to_python();
        assert!(py.contains("os.system('id')"), "{py}");
        for line in py.lines() {
            assert!(
                !line.starts_with("import os"),
                "injected statement: {line:?}"
            );
        }
        assert_only_in_comment(&py, "import os");
        assert_only_in_comment(&py, "os.system('id')");
        assert_flat_python_script(&py);
        assert_python_parses(&py);
    }

    /// A `script_comment` that is not already a comment still renders as
    /// one, so the second line of the script is never a statement.
    #[test]
    fn script_comment_is_forced_into_a_comment() {
        let mut c = chain_fixture();
        c.script_comment = "os.system('id')".to_string();
        let py = c.to_python();
        assert!(
            py.starts_with("#!/usr/bin/env python3\n# os.system('id')\n"),
            "{py}"
        );
        assert_flat_python_script(&py);
    }

    #[test]
    fn json_renderer_roundtrips() {
        let c = chain_fixture();
        let v = c.to_json();
        assert_eq!(v["arch"], "x64");
        assert_eq!(v["word_size"], 8);
        assert_eq!(v["words"][0]["value"], "0x401000");
        assert_eq!(v["words"][0]["kind"], "gadget_addr");
        assert_eq!(v["gadgets"][0]["text"], "pop rdi ; ret");
    }
}
